sudo: required
services: 
  - docker

before_install:
  - docker build -t mzalcmanis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mzalcmanis/docker-react npm run test -- --coverage
