sudo: required
services: 
  - docker

before_install:
  - docker build -t mzalcmanis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mzalcmanis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-989865603753"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY  
  secret_access_key: $AWS_SECRET_KEY